# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Taming Phantom Traffic Jams
tagline:          'A National Science Foundation Cyber Physical Systems Project'
description:      'Phantom Traffic Jams that seemingly occur without cause are due to human driving. Autonomous vehicles might oneday eliminate these jams.'
url:              https://phantomjams.github.io

author:
  name:           'Will Barbour'
  url:            https://barbourww.github.io

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/phantomjams/phantomjams.github.io


